default:
  golem_name: gcsxgsestimate
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/Taylor/Desktop/version_control/GitHub/Grain-Cropping-Systems-Lab/gcsxgsestimate
